% Second-level GLM batch script
% Equivalent to what was done through SPM GUI
% Generated: 16-Jun-2026 17:08:38

addpath('C:\Users\zoele\Documents\MATLAB\spm')
spm('defaults', 'FMRI')
spm_jobman('initcfg')


%% ================================================
%% H1: One-sample t-test (inc > con)
%% ================================================
matlabbatch = {};

% Step 1: Specify design
matlabbatch{1}.spm.stats.factorial_design.dir = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H1_inc_vs_con'};

% Design: One-sample t-test (205 subjects)
matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = {
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0001_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0002_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0003_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0004_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0005_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0006_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0007_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0008_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0009_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0010_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0011_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0012_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0013_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0014_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0015_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0016_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0017_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0018_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0019_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0020_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0021_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0022_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0025_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0026_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0027_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0028_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0029_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0030_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0031_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0033_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0034_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0035_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0036_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0037_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0038_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0039_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0040_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0041_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0042_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0043_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0044_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0045_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0046_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0047_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0048_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0049_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0050_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0051_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0052_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0053_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0054_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0055_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0056_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0057_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0058_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0059_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0060_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0061_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0062_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0063_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0064_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0065_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0066_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0067_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0068_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0069_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0070_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0071_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0072_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0074_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0075_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0076_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0077_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0078_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0079_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0080_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0081_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0082_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0083_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0084_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0085_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0087_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0088_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0090_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0091_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0092_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0093_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0094_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0095_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0096_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0097_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0098_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0099_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0100_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0101_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0102_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0103_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0104_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0105_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0106_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0108_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0109_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0110_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0111_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0112_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0113_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0114_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0115_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0116_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0117_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0118_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0119_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0120_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0121_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0122_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0123_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0124_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0125_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0126_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0127_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0128_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0129_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0130_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0131_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0132_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0133_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0134_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0135_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0136_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0137_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0138_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0139_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0140_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0141_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0142_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0143_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0144_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0145_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0146_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0147_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0148_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0149_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0151_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0153_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0154_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0155_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0156_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0157_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0158_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0159_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0160_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0161_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0162_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0163_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0164_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0165_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0166_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0167_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0168_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0169_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0170_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0171_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0172_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0173_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0174_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0175_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0176_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0177_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0178_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0179_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0180_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0181_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0182_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0183_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0184_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0185_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0186_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0187_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0188_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0190_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0191_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0192_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0193_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0194_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0195_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0196_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0197_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0198_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0199_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0200_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0201_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0202_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0203_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0204_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0205_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0206_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0207_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0208_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0209_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0210_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0211_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0212_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0213_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0214_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\for_gui\H1_all_subs\sub-0215_con_0001.nii'
};

% Masking
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none    = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im             = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em             = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit         = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm        = 1;

% Step 2: Estimate model
matlabbatch{2}.spm.stats.fmri_est.spmmat           = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H1_inc_vs_con\SPM.mat'};
matlabbatch{2}.spm.stats.fmri_est.write_residuals  = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;

% Step 3: Contrasts
matlabbatch{3}.spm.stats.con.spmmat = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H1_inc_vs_con\SPM.mat'};
matlabbatch{3}.spm.stats.con.consess{1}.tcon.name    = 'inc_vs_con';
matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = [1 ];
matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 0;

% Run the batch
spm_jobman('run', matlabbatch)

%% ================================================
%% H2: Two-sample t-test (sex differences)
%% ================================================
matlabbatch = {};

% Step 1: Specify design
matlabbatch{1}.spm.stats.factorial_design.dir = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H2_sex_task'};

% Design: Two-sample t-test (Group1=85, Group2=113)
matlabbatch{1}.spm.stats.factorial_design.des.t2.scans1 = {
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0005_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0003_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0006_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0008_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0016_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0021_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0022_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0026_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0028_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0030_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0040_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0042_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0043_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0044_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0045_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0052_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0053_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0054_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0055_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0058_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0060_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0066_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0067_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0070_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0071_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0074_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0075_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0077_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0078_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0079_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0081_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0082_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0088_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0091_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0092_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0093_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0094_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0097_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0098_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0099_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0100_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0102_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0108_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0109_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0110_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0119_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0121_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0125_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0128_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0131_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0137_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0141_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0143_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0144_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0146_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0148_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0149_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0151_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0153_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0154_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0157_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0158_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0161_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0162_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0166_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0167_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0168_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0169_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0171_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0173_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0174_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0176_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0179_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0183_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0185_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0187_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0188_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0191_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0193_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0201_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0202_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0208_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0211_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0213_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0002_task_vs_baseline\sub-0214_con_0002.nii'
};
matlabbatch{1}.spm.stats.factorial_design.des.t2.scans2 = {
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0009_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0001_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0002_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0004_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0007_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0010_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0012_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0014_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0015_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0018_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0019_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0020_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0025_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0027_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0029_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0033_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0034_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0035_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0036_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0037_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0038_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0039_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0041_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0046_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0047_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0048_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0049_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0050_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0051_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0056_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0057_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0059_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0061_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0062_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0063_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0064_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0065_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0068_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0069_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0072_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0076_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0080_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0083_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0084_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0085_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0087_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0090_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0095_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0096_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0101_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0103_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0104_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0105_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0106_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0111_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0112_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0113_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0114_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0115_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0116_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0117_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0118_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0120_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0122_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0124_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0126_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0127_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0129_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0130_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0132_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0133_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0134_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0135_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0136_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0138_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0139_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0140_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0142_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0145_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0147_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0155_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0159_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0160_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0163_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0164_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0165_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0170_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0172_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0175_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0177_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0178_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0180_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0181_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0182_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0184_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0186_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0190_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0192_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0194_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0195_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0196_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0197_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0198_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0199_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0200_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0203_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0205_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0206_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0207_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0209_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0210_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0212_con_0002.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0002_task_vs_baseline\sub-0215_con_0002.nii'
};
matlabbatch{1}.spm.stats.factorial_design.des.t2.dept     = 0;
matlabbatch{1}.spm.stats.factorial_design.des.t2.variance = 1;
matlabbatch{1}.spm.stats.factorial_design.des.t2.gmsca    = 0;
matlabbatch{1}.spm.stats.factorial_design.des.t2.ancova   = 0;

% Masking
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none    = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im             = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em             = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit         = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm        = 1;

% Step 2: Estimate model
matlabbatch{2}.spm.stats.fmri_est.spmmat           = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H2_sex_task\SPM.mat'};
matlabbatch{2}.spm.stats.fmri_est.write_residuals  = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;

% Step 3: Contrasts
matlabbatch{3}.spm.stats.con.spmmat = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H2_sex_task\SPM.mat'};
matlabbatch{3}.spm.stats.con.consess{1}.tcon.name    = 'males_gt_females';
matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = [1 -1 ];
matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.consess{2}.tcon.name    = 'females_gt_males';
matlabbatch{3}.spm.stats.con.consess{2}.tcon.weights = [-1 1 ];
matlabbatch{3}.spm.stats.con.consess{2}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 0;

% Run the batch
spm_jobman('run', matlabbatch)

%% ================================================
%% H3: Two-sample t-test (Stroop by sex)
%% ================================================
matlabbatch = {};

% Step 1: Specify design
matlabbatch{1}.spm.stats.factorial_design.dir = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H3_sex_stroop'};

% Design: Two-sample t-test (Group1=85, Group2=113)
matlabbatch{1}.spm.stats.factorial_design.des.t2.scans1 = {
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0016_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0003_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0005_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0006_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0008_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0021_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0022_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0026_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0028_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0030_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0040_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0042_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0043_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0044_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0045_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0052_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0053_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0054_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0055_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0058_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0060_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0066_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0067_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0070_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0071_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0074_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0075_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0077_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0078_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0079_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0081_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0082_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0088_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0091_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0092_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0093_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0094_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0097_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0098_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0099_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0100_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0102_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0108_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0109_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0110_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0119_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0121_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0125_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0128_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0131_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0137_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0141_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0143_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0144_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0146_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0148_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0149_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0151_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0153_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0154_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0157_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0158_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0161_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0162_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0166_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0167_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0168_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0169_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0171_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0173_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0174_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0176_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0179_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0183_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0185_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0187_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0188_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0191_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0193_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0201_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0202_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0208_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0211_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0213_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\males\con_0001_inc_vs_con\sub-0214_con_0001.nii'
};
matlabbatch{1}.spm.stats.factorial_design.des.t2.scans2 = {
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0009_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0001_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0002_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0004_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0007_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0010_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0012_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0014_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0015_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0018_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0019_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0020_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0025_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0027_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0029_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0033_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0034_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0035_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0036_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0037_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0038_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0039_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0041_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0046_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0047_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0048_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0049_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0050_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0051_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0056_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0057_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0059_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0061_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0062_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0063_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0064_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0065_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0068_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0069_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0072_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0076_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0080_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0083_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0084_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0085_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0087_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0090_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0095_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0096_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0101_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0103_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0104_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0105_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0106_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0111_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0112_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0113_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0114_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0115_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0116_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0117_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0118_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0120_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0122_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0124_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0126_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0127_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0129_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0130_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0132_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0133_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0134_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0135_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0136_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0138_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0139_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0140_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0142_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0145_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0147_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0155_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0159_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0160_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0163_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0164_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0165_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0170_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0172_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0175_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0177_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0178_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0180_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0181_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0182_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0184_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0186_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0190_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0192_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0194_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0195_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0196_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0197_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0198_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0199_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0200_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0203_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0205_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0206_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0207_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0209_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0210_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0212_con_0001.nii'
    'C:\Users\zoele\Desktop\case_studies_project\results_spm\betas_by_sex\females\con_0001_inc_vs_con\sub-0215_con_0001.nii'
};
matlabbatch{1}.spm.stats.factorial_design.des.t2.dept     = 0;
matlabbatch{1}.spm.stats.factorial_design.des.t2.variance = 1;
matlabbatch{1}.spm.stats.factorial_design.des.t2.gmsca    = 0;
matlabbatch{1}.spm.stats.factorial_design.des.t2.ancova   = 0;

% Masking
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none    = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im             = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em             = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit         = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm        = 1;

% Step 2: Estimate model
matlabbatch{2}.spm.stats.fmri_est.spmmat           = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H3_sex_stroop\SPM.mat'};
matlabbatch{2}.spm.stats.fmri_est.write_residuals  = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;

% Step 3: Contrasts
matlabbatch{3}.spm.stats.con.spmmat = {'C:\Users\zoele\Desktop\case_studies_project\results_spm\second_level\H3_sex_stroop\SPM.mat'};
matlabbatch{3}.spm.stats.con.consess{1}.tcon.name    = 'males_gt_females_stroop ';
matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = [1 -1 ];
matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.consess{2}.tcon.name    = 'females_gt_males_stroop ';
matlabbatch{3}.spm.stats.con.consess{2}.tcon.weights = [-1 1 ];
matlabbatch{3}.spm.stats.con.consess{2}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 0;

% Run the batch
spm_jobman('run', matlabbatch)
